#Parameters for the flight node

# All kinds of limits
limit:
  nav:
    alt_margin: 0.3  # Margin (+/- target) for naviagion
    max_vs:     0.3  # Max vert speed m/s for navigation
  abort:
    altitude:   2.0   # Max allowed altitude, metres
    lost_time:  10.0  # Max time without visual nav data

# PID parameters
pid:
  # Input relative alt, output throttle setting
  altitude:
    target: 1.5   # Metres
    output:
      min:  0.0   # Throttle setting
      max:  1.0   # Throttle setting
      ramp: 2.0   # Throttle / sec
      bias: 0.5   # Throttle setting
    p:      0.09  # 0.20 without bias
    i:      0.00  # 0.06 without bias
    d:      0.00  # 0.02 without bias

  # Input metres ahead, output pitch forward in radians
  pitch:
    target: 0.3   # Metres ahead
    output:
      min:  deg(-10) # Degrees backwards
      max:  deg(+10) # Degrees forward
      ramp: deg(20)  # Degrees / sec
    p:     -0.02     # neg accel fwd / 9.81
    d:      0.09     # accel fwd / 9.81
