#Parameters for the camera node

loop_rate: 18

# Optical flow
of:
  refresh_interval: 10  # frames


frame:
  mask:
    saturation_thr:  82
    mask_edges:      1
    unmasked_x:      640
    unmasked_y:      480

contour:
  rect:
    min_size:      1300
    max_size:      9000
    min_ratio:      2.5
    max_ratio:      5.0
    max_angle:     55.0  # in degrees not radians
