#Parameters for the camera node

# Optical flow
of:
  refresh_interval: 8  # frames


frame:
  mask:
    saturation_thr:  50

contour:
  rect:
    min_size:      1000
    max_size:      4000
    min_ratio:      2.0
    max_ratio:      6.0
    max_angle:     55.0  # in degrees not radians
