#Parameters for the camera node

loop_rate: 25

# Optical flow
of:
  refresh_interval: 10  # frames


frame:
  mask:
    saturation_thr:  80

contour:
  rect:
    min_size:      2000
    max_size:      6000
    min_ratio:      2.5
    max_ratio:      5.0
    max_angle:     55.0  # in degrees not radians
