#Parameters for the camera node

# Optical flow
of:
  refresh_interval: 15  # frames


frame:
  mask:
    saturation_thr: 50
    max_width:     200  # px
    min_contours:    3  # Min number of req contours to shrink the frame

contour:
  outlier_coef:    2.8  # Distance factor
